### ISSUE TITLE
bat file does not work

### ISSUE THREAD

**Issue by masoodarny** [Genoil/ZECMiner#89]
hlw bro thanks for your genoil zec miner..here a thing that when i add 
set gpu fail mode        -f 0
set zero sols watch      -z 1

bat file is not working can you help me bro ....sorry for trouble 

may Allah bless you for your good work

**Comment by whitematrix62** [comment]
You make a lot of nasty comments and you keep opening new issues and expecting people to help you with everything without trying anything yourself. Please stop expecting anyone to spoonfeed you.

**Comment by masoodarny** [comment]
sorry bro ...i will not open a issue again i promise

**Comment by whitematrix62** [comment]
thank you. If you want to set the parameters it should be in the command line. What you are setting is the environment variable. and it's failing because it's using the wrong syntax for batch file. 
So for this case just run it as

genoil.exe -f 0 -z 1 (...)
OR
start genoil.exe -f 0 -z 1 (...)
OR
start cmd /k genoil.exe -f 0 -z 1 (and add your other parameters)

The first one would be blocking meaning it would wait for the genoil.exe to exit before executing the next command. The next 2 would run genoil.exe as separate window but would be slightly more complicated to work with.
